# 错误处理

## 分类

- 可恢复
- 不可恢复 -> BUG

### 不可恢复的错误：panic!()

两种导致panic的方式:

1. 代码中某些行为导致
2. 显式调用`panic!()`宏

默认情况下，panic后，会打印失败信息，展开stack，清理stack，然后退出程序

#### panic后的响应

1. 展开Stack并清理数据
2. 立即终止（abort）

## Backtrace

到达某个点之前所调用的所有函数的列表

设置环境变量：
`RUST_BACKTRACE=`任何不为0的值
必须是Debug模式下才能看到backtrace

## Result

使用Result处理可恢复的错误

## 出现错误时使程序产生panic的常用快捷方式

- unwrap()
  - 用于提取Option或Result类型内部的值
  - 如果是None或Err，程序将panic并终止
- expect()
  - 与unwrap类似，但可以自定义panic信息

一般使用expect，方便输出信息来调试

## 传播错误 - Propagating Errors

将错误返回，由调用该函数的代码来决定如何处理错误

### ? 运算符 operator

使用`?`运算符时

- 如果操作成功，它会解包`OK`并继续执行下一行代码
- 如果操作失败，它会立即返回`Err`，并将错误传播给调用者

使用`?`运算符可以避免大量的`match`或`if let`语句，使代码更简洁

### from函数

把值从一个类型转化为另一个类型

- 定义在`std`的`From trait`上

当函数需要返回一种统一的错误类型来表示整个函数可能失败的所有的情况的时候非常有用。

### 什么时候使用`?`

函数的返回类型与`?`所作用的值的类型兼容。

例如：
函数返回Result<*,E>  --> `?`可作用在 Result<*,E>上
函数返回Option<*>  --> `?`可作用在 Option<*>上

`?`可用于返回类型为`Result`、`Option`或者实现了`FromResidual`的类型的函数内

## main函数也可以返回 Result<T,E>

main函数可返回任何实现了 std::process::Termination trait的类型

--Termination 定义了report函数，它返回ExitCode

## 什么时候使用 Panic？

何时使用？—— 不可恢复的错误场景

- 程序进入不可预期的bad state
- 安全问题 或 代码无法继续执行
- 违反函数契约 或 关键假设

何时使用 Result？—— 可能恢复的错误场景

- 提供恢复选项
- 预期可能发生的错误
- 希望调用者决定如何处理错误